### ISSUE TITLE
Implementation for Custom Map and Data

### ISSUE THREAD

**Issue by batuhanaavci** [jureviciusr/particle-match#4]
Hi,
I really appreciate the research and code, I think I have learned a lot about visual odometry, particle filter and computer vision concepts.This was very insightful for me but I have something on my mind: I would like to go further and try this project with custom map and data. However, when I try to change the .tif file with another .tif example which I have found, I got some errors. How can I basically customize this project for my map area and image data? Would you like to summarize generally the steps for this custom configuration? (I am aware of that I will get inconsistent result since simulations has done with different maps, but I just want to change the map.)

**Comment by jureviciusr** [comment]
Hi, 
the map loading is using a geotiff format image, I guess you are getting errors, since you are using a regular tiff image without geographical information. To use a custom map you only need to have rgb data and geographical coordinates which represent the pixel location of corners of the image, you can look here:
https://github.com/jureviciusr/particle-match/blob/master/dataset_reader/include/fastmatch-dataset/Map.hpp

So you just need to load images and provide the geographical coordinates. If you don't have them, you can pass some emulated coordinates, although in that case output of the algorithm can be correct to pixel values, but it won't map to anything related in real-world geographical measurements.

**Comment by batuhanaavci** [comment]
Thanks for your reply. Actually, I used an example from Internet which includes both RGB data and geographical coordinates. It has already GeoTiff format. I got an error about the region of interest:

cv::Exception'
  what():  OpenCV(4.2.0) /home/bavci/opencv-4.2.0/modules/core/src/matrix.cpp:465: error: (-215:Assertion failed) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function 'Mat'

I think that region of interest falls in the outside of image data, but I couldn't find a proper solution. Would you want to make a suggestion?

**Comment by fliochord** [comment]
ananı avradımı siktigim noldu amcık
